---

#### This playbook creates a ASM policy

# Uses Dynamic Inventory to discover Instance IPs
# - hosts: bigips
- hosts: tag_Name_BIG_IP_Autoscale_Instance__{{deploymentName}}_master
  connection: local
  gather_facts: False
  environment:
      F5_SERVER: "{{ ansible_ssh_host }}"
      F5_USER: "{{ bigip_user }}"
      F5_PASSWORD: "{{ bigip_password }}" # inherit from vault
      F5_SERVER_PORT: "{{ bigip_port }}"
      F5_VALIDATE_CERTS: "{{ validate_certs }}"
  roles:
    - bigip_base_asm
  post_tasks:
    - name: Save the running BIG-IP configuration to disk
      delegate_to: localhost
      bigip_config:
        save: True
      register: result